# Generated by Django 5.0 on 2024-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
