# Generated by Django 5.0 on 2024-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_creation_remove_news_date_news_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='anons',
            field=models.CharField(max_length=30, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Описание'),
        ),
    ]
