# Generated by Django 5.0 on 2024-01-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_anons_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='anons',
            field=models.CharField(max_length=60, verbose_name='Анонс'),
        ),
    ]
