# Generated by Django 5.0 on 2024-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_klass'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
