# Generated by Django 5.0 on 2024-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_klass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
