# Generated by Django 5.0 on 2024-01-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_klass_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klass',
        ),
    ]
