# Generated by Django 5.0 on 2024-01-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
